"""Character pool data — hand-curated, recognizability-tiered.

WHY THIS IS NOT AUTO-GENERATED
------------------------------
This file was originally produced from Jikan (MyAnimeList) using its `role`
field ("Main" / "Supporting") as the difficulty signal. That was wrong, and
Phase 3.12 replaced it. `role` measures *narrative centrality inside one
show*, which is not what this game actually needs to know. The game needs to
know: **will the people around this table recognise this character?**

Those come apart constantly. Jikan calls Vegeta, Sasuke, Sakura, Mikasa,
Itachi and Gojo "Supporting" — they are among the most recognisable anime
characters alive. It calls the lead of a niche show "Main" when most players
have never heard of them. Tiering on `role` therefore made easy mode both
repetitive (often 1-3 protagonists per show) and wrong.

THE TWO SIGNALS
---------------
Recognisability is the product of two independent things, so both are stored
separately and combined by characters.py rather than being collapsed into a
single hand-written difficulty per character:

  reach       -- how far the SHOW itself penetrated outside anime fandom.
                 "mega"    a non-anime-watcher would plausibly know it
                 "popular" widely known among anime watchers, big footprint
                 "cult"    beloved/acclaimed but niche, old, or fandom-only

  prominence  -- how central the CHARACTER is within that show.
                 "core"    protagonist, main rival, primary antagonist, core
                           team member, or an iconic breakout who transcends
                           their actual screen time (Levi, Rem, Megumin)
                 "notable" significant recurring character; a viewer of the
                           show knows them, a non-viewer probably doesn't
                 "deep"    minor, one-off, or background — a genuine deep cut

Keeping them separate means every difficulty is auditable: you can see *why*
a character landed where they did, and re-tiering a whole show is one edit to
its `reach` rather than a pass over every character. The combining matrix
lives in characters.py.

CALIBRATION
-----------
Deliberately generous with "core" on mega-reach shows — that is the entire
point of the redesign. A Naruto or Dragon Ball character who shows up on
merchandise and in memes belongs in easy mode even if MAL calls them
supporting. Conversely "core" on a cult show only reaches medium, because
being the lead of Steins;Gate does not make you recognisable to a table of
casual players.

KonoSuba is deliberately kept at "cult" reach on the project owner's explicit
call ("more of a niche goonerish anime"), even though its viewership numbers
would arguably support "popular". Its cast therefore tops out at medium.

`mal_id: None` marks an entry as curated from knowledge rather than confirmed
via a live Jikan lookup. Every entry is currently None: Jikan was down during
the original curation, and Phase 3.12 re-tiered by hand regardless, so a live
id would imply a precision this data does not have. See build_character_pool.py
for how a future live pull is meant to interact with this file (it writes a
draft for review — it must NOT overwrite this one, or the curation is lost).
"""

ANIME_POOL = [
    # ---------------------------------------------------------------- mega
    {
        "title": "Naruto",
        "mal_id": None,
        "genres": ["Action", "Adventure"],
        "reach": "mega",
        "synopsis": "An orphaned ninja with a sealed demon fox inside him trains to become his village's leader while chasing the friend who abandoned it.",
        "characters": [
            {"name": "Naruto Uzumaki", "prominence": "core"},
            {"name": "Sasuke Uchiha", "prominence": "core"},
            {"name": "Sakura Haruno", "prominence": "core"},
            {"name": "Kakashi Hatake", "prominence": "core"},
            {"name": "Itachi Uchiha", "prominence": "core"},
            {"name": "Gaara", "prominence": "core"},
            {"name": "Hinata Hyuga", "prominence": "core"},
            {"name": "Rock Lee", "prominence": "core"},
            {"name": "Jiraiya", "prominence": "core"},
            {"name": "Orochimaru", "prominence": "core"},
            {"name": "Shikamaru Nara", "prominence": "core"},
            {"name": "Tsunade", "prominence": "core"},
            {"name": "Minato Namikaze", "prominence": "notable"},
            {"name": "Neji Hyuga", "prominence": "notable"},
            {"name": "Kiba Inuzuka", "prominence": "notable"},
            {"name": "Choji Akimichi", "prominence": "notable"},
            {"name": "Ino Yamanaka", "prominence": "notable"},
            {"name": "Might Guy", "prominence": "notable"},
            {"name": "Kabuto Yakushi", "prominence": "notable"},
            {"name": "Iruka Umino", "prominence": "notable"},
            {"name": "Konohamaru Sarutobi", "prominence": "deep"},
            {"name": "Shino Aburame", "prominence": "deep"},
            {"name": "Tenten", "prominence": "deep"},
            {"name": "Asuma Sarutobi", "prominence": "deep"},
            {"name": "Kurenai Yuhi", "prominence": "deep"},
            {"name": "Shizune", "prominence": "deep"},
            {"name": "Anko Mitarashi", "prominence": "deep"},
        ],
    },
    {
        "title": "One Piece",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "reach": "mega",
        "synopsis": "A rubber-bodied pirate and his crew sail a vast ocean hunting the world's greatest treasure, gathering misfits with strange powers.",
        "characters": [
            {"name": "Monkey D. Luffy", "prominence": "core"},
            {"name": "Roronoa Zoro", "prominence": "core"},
            {"name": "Nami", "prominence": "core"},
            {"name": "Sanji", "prominence": "core"},
            {"name": "Usopp", "prominence": "core"},
            {"name": "Tony Tony Chopper", "prominence": "core"},
            {"name": "Nico Robin", "prominence": "core"},
            {"name": "Portgas D. Ace", "prominence": "core"},
            {"name": "Shanks", "prominence": "core"},
            {"name": "Trafalgar Law", "prominence": "core"},
            {"name": "Franky", "prominence": "notable"},
            {"name": "Brook", "prominence": "notable"},
            {"name": "Jinbe", "prominence": "notable"},
            {"name": "Boa Hancock", "prominence": "notable"},
            {"name": "Buggy", "prominence": "notable"},
            {"name": "Sabo", "prominence": "notable"},
            {"name": "Bartholomew Kuma", "prominence": "deep"},
            {"name": "Koby", "prominence": "deep"},
        ],
    },
    {
        "title": "Dragon Ball Z",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "reach": "mega",
        "synopsis": "An alien-raised martial artist and his friends defend Earth from ever-stronger warriors through tournaments and planet-scale battles.",
        "characters": [
            {"name": "Goku", "prominence": "core"},
            {"name": "Vegeta", "prominence": "core"},
            {"name": "Gohan", "prominence": "core"},
            {"name": "Piccolo", "prominence": "core"},
            {"name": "Frieza", "prominence": "core"},
            {"name": "Krillin", "prominence": "core"},
            {"name": "Bulma", "prominence": "core"},
            {"name": "Cell", "prominence": "core"},
            {"name": "Majin Buu", "prominence": "core"},
            {"name": "Trunks", "prominence": "notable"},
            {"name": "Master Roshi", "prominence": "notable"},
            {"name": "Tien Shinhan", "prominence": "notable"},
            {"name": "Yamcha", "prominence": "notable"},
            {"name": "Chi-Chi", "prominence": "notable"},
            {"name": "Android 18", "prominence": "notable"},
            {"name": "Videl", "prominence": "deep"},
            {"name": "Chiaotzu", "prominence": "deep"},
            {"name": "Mr. Satan", "prominence": "deep"},
        ],
    },
    {
        "title": "Attack on Titan",
        "mal_id": None,
        "genres": ["Action", "Drama", "Fantasy", "Mystery"],
        "reach": "mega",
        "synopsis": "Humanity hides behind enormous walls from man-eating giants, until the walls break and soldiers fight back with grappling gear.",
        "characters": [
            {"name": "Eren Yeager", "prominence": "core"},
            {"name": "Mikasa Ackerman", "prominence": "core"},
            {"name": "Armin Arlert", "prominence": "core"},
            {"name": "Levi Ackerman", "prominence": "core"},
            {"name": "Erwin Smith", "prominence": "core"},
            {"name": "Historia Reiss", "prominence": "notable"},
            {"name": "Reiner Braun", "prominence": "notable"},
            {"name": "Annie Leonhart", "prominence": "core"},
            {"name": "Jean Kirstein", "prominence": "notable"},
            {"name": "Sasha Blouse", "prominence": "notable"},
            {"name": "Hange Zoe", "prominence": "notable"},
            {"name": "Connie Springer", "prominence": "notable"},
            {"name": "Ymir", "prominence": "deep"},
            {"name": "Bertholdt Hoover", "prominence": "deep"},
            {"name": "Marco Bott", "prominence": "deep"},
            {"name": "Pieck Finger", "prominence": "deep"},
        ],
    },
    {
        "title": "Death Note",
        "mal_id": None,
        "genres": ["Mystery", "Psychological", "Supernatural"],
        "reach": "mega",
        "synopsis": "A brilliant student finds a notebook that kills anyone whose name he writes in it, and a rival detective tries to unmask him.",
        "characters": [
            {"name": "Light Yagami", "prominence": "core"},
            {"name": "L", "prominence": "core"},
            {"name": "Ryuk", "prominence": "core"},
            {"name": "Misa Amane", "prominence": "core"},
            {"name": "Near", "prominence": "notable"},
            {"name": "Mello", "prominence": "notable"},
            # Death Note's shinigami Rem is deliberately omitted: Re:Zero's Rem
            # is far better known, and two different characters sharing one name
            # is genuinely bad in a game whose win condition is naming one.
            {"name": "Soichiro Yagami", "prominence": "deep"},
            {"name": "Teru Mikami", "prominence": "deep"},
            {"name": "Touta Matsuda", "prominence": "deep"},
        ],
    },
    {
        "title": "Demon Slayer: Kimetsu no Yaiba",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "reach": "mega",
        "synopsis": "After demons slaughter his family and turn his sister into one, a boy joins a sword corps hunting them to find a cure.",
        "characters": [
            {"name": "Tanjiro Kamado", "prominence": "core"},
            {"name": "Nezuko Kamado", "prominence": "core"},
            {"name": "Zenitsu Agatsuma", "prominence": "core"},
            {"name": "Inosuke Hashibira", "prominence": "core"},
            {"name": "Kyojuro Rengoku", "prominence": "core"},
            {"name": "Muzan Kibutsuji", "prominence": "core"},
            {"name": "Giyu Tomioka", "prominence": "core"},
            {"name": "Akaza", "prominence": "notable"},
            {"name": "Shinobu Kocho", "prominence": "core"},
            {"name": "Tengen Uzui", "prominence": "notable"},
            {"name": "Kanao Tsuyuri", "prominence": "notable"},
            {"name": "Mitsuri Kanroji", "prominence": "notable"},
            {"name": "Obanai Iguro", "prominence": "deep"},
            {"name": "Sanemi Shinazugawa", "prominence": "deep"},
            {"name": "Genya Shinazugawa", "prominence": "deep"},
        ],
    },
    {
        "title": "Jujutsu Kaisen",
        "mal_id": None,
        "genres": ["Action", "Fantasy", "Horror"],
        "reach": "mega",
        "synopsis": "A student swallows a cursed finger and shares his body with a monstrous spirit while training among sorcerers who exorcise curses.",
        "characters": [
            {"name": "Yuji Itadori", "prominence": "core"},
            {"name": "Megumi Fushiguro", "prominence": "core"},
            {"name": "Nobara Kugisaki", "prominence": "core"},
            {"name": "Satoru Gojo", "prominence": "core"},
            {"name": "Sukuna", "prominence": "core"},
            {"name": "Nanami Kento", "prominence": "core"},
            {"name": "Maki Zenin", "prominence": "notable"},
            {"name": "Yuta Okkotsu", "prominence": "core"},
            {"name": "Toji Fushiguro", "prominence": "core"},
            {"name": "Toge Inumaki", "prominence": "deep"},
            {"name": "Panda", "prominence": "deep"},
            {"name": "Kasumi Miwa", "prominence": "deep"},
        ],
    },
    {
        "title": "My Hero Academia",
        "mal_id": None,
        "genres": ["Action", "Adventure"],
        "reach": "mega",
        "synopsis": "In a world where nearly everyone has superpowers, a powerless boy inherits one and enrols in a school for heroes.",
        "characters": [
            {"name": "Izuku Midoriya", "prominence": "core"},
            {"name": "Katsuki Bakugo", "prominence": "core"},
            {"name": "All Might", "prominence": "core"},
            {"name": "Shoto Todoroki", "prominence": "core"},
            {"name": "Ochaco Uraraka", "prominence": "core"},
            {"name": "Tenya Iida", "prominence": "notable"},
            {"name": "Eijiro Kirishima", "prominence": "notable"},
            {"name": "Shota Aizawa", "prominence": "notable"},
            {"name": "Tomura Shigaraki", "prominence": "notable"},
            {"name": "Himiko Toga", "prominence": "notable"},
            {"name": "Endeavor", "prominence": "notable"},
            {"name": "Tsuyu Asui", "prominence": "deep"},
            {"name": "Denki Kaminari", "prominence": "deep"},
            {"name": "Momo Yaoyorozu", "prominence": "deep"},
            {"name": "Mina Ashido", "prominence": "deep"},
            {"name": "Fumikage Tokoyami", "prominence": "deep"},
        ],
    },
    {
        "title": "Chainsaw Man",
        "mal_id": None,
        "genres": ["Action", "Fantasy", "Horror"],
        "reach": "mega",
        "synopsis": "A destitute teenager fused with his chainsaw dog-demon becomes a government devil hunter, chasing a normal life he never gets.",
        "characters": [
            {"name": "Denji", "prominence": "core"},
            {"name": "Power", "prominence": "core"},
            {"name": "Makima", "prominence": "core"},
            {"name": "Aki Hayakawa", "prominence": "core"},
            {"name": "Reze", "prominence": "core"},
            {"name": "Pochita", "prominence": "notable"},
            {"name": "Himeno", "prominence": "notable"},
            {"name": "Kishibe", "prominence": "notable"},
            {"name": "Angel Devil", "prominence": "notable"},
            {"name": "Kobeni Higashiyama", "prominence": "deep"},
            {"name": "Hirokazu Arai", "prominence": "deep"},
        ],
    },
    {
        "title": "Spy x Family",
        "mal_id": None,
        "genres": ["Action", "Comedy", "Slice of Life"],
        "reach": "mega",
        "synopsis": "A master spy fakes a family for a mission, unaware his adopted daughter reads minds and his wife is an assassin.",
        "characters": [
            {"name": "Anya Forger", "prominence": "core"},
            {"name": "Loid Forger", "prominence": "core"},
            {"name": "Yor Forger", "prominence": "core"},
            {"name": "Bond Forger", "prominence": "notable"},
            {"name": "Yuri Briar", "prominence": "notable"},
            {"name": "Damian Desmond", "prominence": "notable"},
            {"name": "Fiona Frost", "prominence": "deep"},
            {"name": "Becky Blackbell", "prominence": "deep"},
            {"name": "Franky Franklin", "prominence": "deep"},
        ],
    },
    {
        "title": "Pokemon",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Comedy", "Fantasy"],
        "reach": "mega",
        "synopsis": "A boy and his electric mouse travel the world catching creatures and challenging gyms, chased by a bumbling criminal trio.",
        "characters": [
            {"name": "Pikachu", "prominence": "core"},
            {"name": "Ash Ketchum", "prominence": "core"},
            {"name": "Misty", "prominence": "core"},
            {"name": "Brock", "prominence": "core"},
            {"name": "Charizard", "prominence": "core"},
            {"name": "Mewtwo", "prominence": "core"},
            {"name": "Eevee", "prominence": "core"},
            {"name": "Jessie", "prominence": "notable"},
            {"name": "James", "prominence": "notable"},
            {"name": "Meowth", "prominence": "notable"},
            {"name": "Gary Oak", "prominence": "notable"},
            {"name": "Professor Oak", "prominence": "notable"},
            {"name": "Togepi", "prominence": "deep"},
            {"name": "Nurse Joy", "prominence": "deep"},
        ],
    },
    {
        "title": "Sailor Moon",
        "mal_id": None,
        "genres": ["Action", "Fantasy", "Romance"],
        "reach": "popular",
        "synopsis": "A clumsy schoolgirl transforms into a sailor-suited guardian and gathers a team of magical girls to defend Earth.",
        "characters": [
            {"name": "Usagi Tsukino", "prominence": "core"},
            {"name": "Mamoru Chiba", "prominence": "core"},
            {"name": "Luna", "prominence": "core"},
            {"name": "Rei Hino", "prominence": "notable"},
            {"name": "Ami Mizuno", "prominence": "notable"},
            {"name": "Makoto Kino", "prominence": "notable"},
            {"name": "Minako Aino", "prominence": "notable"},
            {"name": "Chibiusa", "prominence": "notable"},
            {"name": "Artemis", "prominence": "deep"},
            {"name": "Setsuna Meiou", "prominence": "deep"},
            {"name": "Haruka Tenou", "prominence": "deep"},
        ],
    },
    {
        "title": "Spirited Away",
        "mal_id": None,
        "genres": ["Adventure", "Fantasy", "Supernatural"],
        "reach": "mega",
        "synopsis": "A girl wanders into a spirit world and must work in a bathhouse for the gods to free her parents.",
        "characters": [
            {"name": "Chihiro Ogino", "prominence": "core"},
            {"name": "Haku", "prominence": "core"},
            {"name": "No-Face", "prominence": "core"},
            {"name": "Yubaba", "prominence": "notable"},
            {"name": "Lin", "prominence": "notable"},
            {"name": "Kamaji", "prominence": "notable"},
            {"name": "Zeniba", "prominence": "deep"},
            {"name": "Boh", "prominence": "deep"},
        ],
    },
    {
        "title": "My Neighbor Totoro",
        "mal_id": None,
        "genres": ["Adventure", "Fantasy", "Slice of Life"],
        "reach": "mega",
        "synopsis": "Two sisters who move to the countryside befriend a giant forest spirit while their mother is ill.",
        "characters": [
            {"name": "Totoro", "prominence": "core"},
            {"name": "Satsuki Kusakabe", "prominence": "core"},
            {"name": "Mei Kusakabe", "prominence": "core"},
            {"name": "Catbus", "prominence": "notable"},
            {"name": "Tatsuo Kusakabe", "prominence": "deep"},
            {"name": "Kanta Ogaki", "prominence": "deep"},
        ],
    },

    # ------------------------------------------------------------- popular
    {
        "title": "Fullmetal Alchemist: Brotherhood",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Drama", "Fantasy"],
        "reach": "popular",
        "synopsis": "Two brothers maimed by a forbidden alchemy ritual search for a stone to restore their bodies, uncovering a national conspiracy.",
        "characters": [
            {"name": "Edward Elric", "prominence": "core"},
            {"name": "Alphonse Elric", "prominence": "core"},
            {"name": "Roy Mustang", "prominence": "core"},
            {"name": "Winry Rockbell", "prominence": "notable"},
            {"name": "Riza Hawkeye", "prominence": "notable"},
            {"name": "Scar", "prominence": "notable"},
            {"name": "King Bradley", "prominence": "notable"},
            {"name": "Envy", "prominence": "notable"},
            {"name": "Greed", "prominence": "notable"},
            {"name": "Alex Louis Armstrong", "prominence": "notable"},
            {"name": "Maes Hughes", "prominence": "notable"},
            {"name": "Ling Yao", "prominence": "deep"},
            {"name": "May Chang", "prominence": "deep"},
            {"name": "Izumi Curtis", "prominence": "deep"},
            {"name": "Olivier Mira Armstrong", "prominence": "deep"},
        ],
    },
    {
        "title": "Bleach",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "reach": "mega",
        "synopsis": "A teenager who can see ghosts inherits a soul reaper's powers and defends the living from monstrous spirits.",
        "characters": [
            {"name": "Ichigo Kurosaki", "prominence": "core"},
            {"name": "Rukia Kuchiki", "prominence": "core"},
            {"name": "Sosuke Aizen", "prominence": "core"},
            {"name": "Orihime Inoue", "prominence": "notable"},
            {"name": "Uryu Ishida", "prominence": "notable"},
            {"name": "Renji Abarai", "prominence": "notable"},
            {"name": "Byakuya Kuchiki", "prominence": "notable"},
            {"name": "Toshiro Hitsugaya", "prominence": "notable"},
            {"name": "Kenpachi Zaraki", "prominence": "notable"},
            {"name": "Yasutora Sado", "prominence": "notable"},
            {"name": "Kisuke Urahara", "prominence": "notable"},
            {"name": "Grimmjow Jaegerjaquez", "prominence": "deep"},
            {"name": "Yoruichi Shihouin", "prominence": "deep"},
            {"name": "Gin Ichimaru", "prominence": "deep"},
        ],
    },
    {
        "title": "Hunter x Hunter",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "reach": "popular",
        "synopsis": "A boy sits a brutal licensing exam to become a Hunter and find his absent father, befriending an assassin's heir.",
        "characters": [
            {"name": "Gon Freecss", "prominence": "core"},
            {"name": "Killua Zoldyck", "prominence": "core"},
            {"name": "Kurapika", "prominence": "core"},
            {"name": "Hisoka Morow", "prominence": "core"},
            {"name": "Leorio Paradinight", "prominence": "core"},
            {"name": "Chrollo Lucilfer", "prominence": "notable"},
            {"name": "Meruem", "prominence": "notable"},
            {"name": "Ging Freecss", "prominence": "notable"},
            {"name": "Biscuit Krueger", "prominence": "deep"},
            {"name": "Netero", "prominence": "deep"},
            {"name": "Illumi Zoldyck", "prominence": "deep"},
        ],
    },
    {
        "title": "One Punch Man",
        "mal_id": None,
        "genres": ["Action", "Comedy", "Sci-Fi"],
        "reach": "mega",
        "synopsis": "A bored hero who defeats any monster in a single punch looks for a real challenge in a world of ranked professional heroes.",
        "characters": [
            {"name": "Saitama", "prominence": "core"},
            {"name": "Genos", "prominence": "core"},
            {"name": "Tatsumaki", "prominence": "notable"},
            {"name": "Fubuki", "prominence": "notable"},
            {"name": "Mumen Rider", "prominence": "notable"},
            {"name": "Garou", "prominence": "notable"},
            {"name": "King", "prominence": "notable"},
            {"name": "Bang", "prominence": "deep"},
            {"name": "Speed-o'-Sound Sonic", "prominence": "deep"},
            {"name": "Boros", "prominence": "deep"},
        ],
    },
    {
        "title": "Haikyuu!!",
        "mal_id": None,
        "genres": ["Sports", "Comedy", "Drama"],
        "reach": "popular",
        "synopsis": "A short, relentless boy joins his high school volleyball team and forms an explosive partnership with a genius setter.",
        "characters": [
            {"name": "Shoyo Hinata", "prominence": "core"},
            {"name": "Tobio Kageyama", "prominence": "core"},
            {"name": "Tooru Oikawa", "prominence": "notable"},
            {"name": "Kenma Kozume", "prominence": "notable"},
            {"name": "Kei Tsukishima", "prominence": "notable"},
            {"name": "Yu Nishinoya", "prominence": "notable"},
            {"name": "Kotaro Bokuto", "prominence": "notable"},
            {"name": "Daichi Sawamura", "prominence": "deep"},
            {"name": "Koshi Sugawara", "prominence": "deep"},
            {"name": "Ryunosuke Tanaka", "prominence": "deep"},
            {"name": "Asahi Azumane", "prominence": "deep"},
        ],
    },
    {
        "title": "Tokyo Ghoul",
        "mal_id": None,
        "genres": ["Action", "Drama", "Horror", "Mystery"],
        "reach": "popular",
        "synopsis": "A student is transplanted with ghoul organs and must survive between humans and the flesh-eating creatures hiding among them.",
        "characters": [
            {"name": "Ken Kaneki", "prominence": "core"},
            {"name": "Touka Kirishima", "prominence": "core"},
            {"name": "Rize Kamishiro", "prominence": "notable"},
            {"name": "Juzo Suzuya", "prominence": "notable"},
            {"name": "Shuu Tsukiyama", "prominence": "notable"},
            {"name": "Hideyoshi Nagachika", "prominence": "notable"},
            {"name": "Kishou Arima", "prominence": "deep"},
            {"name": "Renji Yomo", "prominence": "deep"},
            {"name": "Yoshimura", "prominence": "deep"},
        ],
    },
    {
        "title": "Sword Art Online",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy", "Romance"],
        "reach": "popular",
        "synopsis": "Players are trapped inside a virtual reality MMO where dying in the game kills them in real life.",
        "characters": [
            {"name": "Kirito", "prominence": "core"},
            {"name": "Asuna Yuuki", "prominence": "core"},
            {"name": "Sinon", "prominence": "notable"},
            {"name": "Leafa", "prominence": "notable"},
            {"name": "Klein", "prominence": "notable"},
            {"name": "Silica", "prominence": "deep"},
            {"name": "Lisbeth", "prominence": "deep"},
            {"name": "Yui", "prominence": "deep"},
            {"name": "Heathcliff", "prominence": "deep"},
        ],
    },
    {
        "title": "Code Geass: Lelouch of the Rebellion",
        "mal_id": None,
        "genres": ["Action", "Drama", "Mecha", "Sci-Fi"],
        "reach": "popular",
        "synopsis": "An exiled prince gains the power to command absolute obedience and leads a masked rebellion against an empire from inside a mecha war.",
        "characters": [
            {"name": "Lelouch Lamperouge", "prominence": "core"},
            {"name": "C.C.", "prominence": "core"},
            {"name": "Suzaku Kururugi", "prominence": "core"},
            {"name": "Kallen Kozuki", "prominence": "notable"},
            {"name": "Nunnally Lamperouge", "prominence": "notable"},
            {"name": "Shirley Fenette", "prominence": "deep"},
            {"name": "Rolo Lamperouge", "prominence": "deep"},
            {"name": "Charles zi Britannia", "prominence": "deep"},
        ],
    },
    {
        "title": "Neon Genesis Evangelion",
        "mal_id": None,
        "genres": ["Action", "Drama", "Mecha", "Psychological", "Sci-Fi"],
        "reach": "popular",
        "synopsis": "A withdrawn boy is made to pilot a biomechanical mecha against enigmatic beings, in a story as much about depression as war.",
        "characters": [
            {"name": "Shinji Ikari", "prominence": "core"},
            {"name": "Rei Ayanami", "prominence": "core"},
            {"name": "Asuka Langley Soryu", "prominence": "core"},
            {"name": "Misato Katsuragi", "prominence": "core"},
            {"name": "Gendo Ikari", "prominence": "notable"},
            {"name": "Kaworu Nagisa", "prominence": "notable"},
            {"name": "Ritsuko Akagi", "prominence": "deep"},
            {"name": "Toji Suzuhara", "prominence": "deep"},
            {"name": "Pen Pen", "prominence": "deep"},
        ],
    },
    {
        "title": "Cowboy Bebop",
        "mal_id": None,
        "genres": ["Action", "Sci-Fi", "Space", "Adventure"],
        "reach": "cult",
        "synopsis": "A jazz-scored crew of bounty hunters drifts through the solar system in a beat-up ship, each running from their own past.",
        "characters": [
            {"name": "Spike Spiegel", "prominence": "core"},
            {"name": "Faye Valentine", "prominence": "core"},
            {"name": "Jet Black", "prominence": "core"},
            {"name": "Ed", "prominence": "notable"},
            {"name": "Ein", "prominence": "notable"},
            {"name": "Vicious", "prominence": "deep"},
            {"name": "Julia", "prominence": "deep"},
        ],
    },
    {
        "title": "Fairy Tail",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "reach": "popular",
        "synopsis": "A rowdy guild of wizards takes jobs together, led by a fire-breathing dragon slayer and a celestial spirit summoner.",
        "characters": [
            {"name": "Natsu Dragneel", "prominence": "core"},
            {"name": "Lucy Heartfilia", "prominence": "core"},
            {"name": "Erza Scarlet", "prominence": "core"},
            {"name": "Gray Fullbuster", "prominence": "core"},
            {"name": "Happy", "prominence": "core"},
            {"name": "Wendy Marvell", "prominence": "notable"},
            {"name": "Gajeel Redfox", "prominence": "notable"},
            {"name": "Juvia Lockser", "prominence": "notable"},
            {"name": "Laxus Dreyar", "prominence": "deep"},
            {"name": "Mirajane Strauss", "prominence": "deep"},
            {"name": "Makarov Dreyar", "prominence": "deep"},
        ],
    },
    {
        "title": "Mob Psycho 100",
        "mal_id": None,
        "genres": ["Action", "Comedy", "Supernatural"],
        "reach": "popular",
        "synopsis": "An overwhelmingly powerful psychic middle-schooler tries to live normally while working for a con-man exorcist.",
        "characters": [
            {"name": "Shigeo Kageyama", "prominence": "core"},
            {"name": "Reigen Arataka", "prominence": "core"},
            {"name": "Dimple", "prominence": "notable"},
            {"name": "Ritsu Kageyama", "prominence": "notable"},
            {"name": "Teruki Hanazawa", "prominence": "notable"},
            {"name": "Tome Kurata", "prominence": "deep"},
            {"name": "Sho Suzuki", "prominence": "deep"},
        ],
    },
    {
        "title": "Re:Zero - Starting Life in Another World",
        "mal_id": None,
        "genres": ["Drama", "Fantasy", "Psychological", "Thriller"],
        "reach": "popular",
        "synopsis": "A boy pulled into a fantasy world discovers that dying rewinds him to a checkpoint, forcing him through the same horrors repeatedly.",
        "characters": [
            {"name": "Subaru Natsuki", "prominence": "core"},
            {"name": "Emilia", "prominence": "core"},
            {"name": "Rem", "prominence": "core"},
            {"name": "Ram", "prominence": "notable"},
            {"name": "Beatrice", "prominence": "notable"},
            {"name": "Puck", "prominence": "notable"},
            {"name": "Roswaal L Mathers", "prominence": "deep"},
            {"name": "Crusch Karsten", "prominence": "deep"},
            {"name": "Felt", "prominence": "deep"},
        ],
    },
    {
        "title": "Frieren: Beyond Journey's End",
        "mal_id": None,
        "genres": ["Adventure", "Drama", "Fantasy"],
        "reach": "popular",
        "synopsis": "An elf mage outlives the hero's party she travelled with and retraces their journey, learning what her human friends meant to her.",
        "characters": [
            {"name": "Frieren", "prominence": "core"},
            {"name": "Fern", "prominence": "core"},
            {"name": "Stark", "prominence": "core"},
            {"name": "Himmel", "prominence": "notable"},
            {"name": "Heiter", "prominence": "notable"},
            {"name": "Eisen", "prominence": "notable"},
            {"name": "Serie", "prominence": "deep"},
            {"name": "Sein", "prominence": "deep"},
        ],
    },
    {
        "title": "Solo Leveling",
        "mal_id": None,
        "genres": ["Action", "Fantasy"],
        "reach": "mega",
        "synopsis": "The world's weakest monster-hunter gains a video-game-like levelling system and climbs from bottom-ranked to unstoppable.",
        "characters": [
            {"name": "Sung Jinwoo", "prominence": "core"},
            {"name": "Cha Hae-In", "prominence": "core"},
            {"name": "Go Gun-hee", "prominence": "notable"},
            {"name": "Baek Yoonho", "prominence": "deep"},
            {"name": "Woo Jinchul", "prominence": "deep"},
        ],
    },
    {
        "title": "Your Name",
        "mal_id": None,
        "genres": ["Romance", "Drama", "Supernatural"],
        "reach": "mega",
        "synopsis": "Two teenagers who have never met begin swapping bodies across a distance neither of them understands.",
        "characters": [
            {"name": "Taki Tachibana", "prominence": "core"},
            {"name": "Mitsuha Miyamizu", "prominence": "core"},
            {"name": "Katsuhiko Teshigawara", "prominence": "deep"},
            {"name": "Sayaka Natori", "prominence": "deep"},
            {"name": "Yotsuha Miyamizu", "prominence": "deep"},
        ],
    },
    {
        "title": "Fate/Zero",
        "mal_id": None,
        "genres": ["Action", "Fantasy", "Supernatural"],
        "reach": "popular",
        "synopsis": "Seven mages summon historical heroes as servants to fight a lethal tournament for a wish-granting grail.",
        "characters": [
            {"name": "Saber", "prominence": "core"},
            {"name": "Gilgamesh", "prominence": "core"},
            {"name": "Kiritsugu Emiya", "prominence": "core"},
            {"name": "Kirei Kotomine", "prominence": "notable"},
            {"name": "Iskandar", "prominence": "notable"},
            {"name": "Waver Velvet", "prominence": "notable"},
            {"name": "Irisviel von Einzbern", "prominence": "deep"},
            {"name": "Kariya Matou", "prominence": "deep"},
            {"name": "Tokiomi Tohsaka", "prominence": "deep"},
        ],
    },
    {
        "title": "JoJo's Bizarre Adventure",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Supernatural"],
        "reach": "mega",
        "synopsis": "A generational saga of a family feuding with a vampire, where fighters manifest personified spirit powers and pose dramatically.",
        "characters": [
            {"name": "Jotaro Kujo", "prominence": "core"},
            {"name": "Dio Brando", "prominence": "core"},
            {"name": "Joseph Joestar", "prominence": "core"},
            {"name": "Giorno Giovanna", "prominence": "core"},
            {"name": "Jonathan Joestar", "prominence": "notable"},
            {"name": "Josuke Higashikata", "prominence": "notable"},
            {"name": "Yoshikage Kira", "prominence": "notable"},
            {"name": "Noriaki Kakyoin", "prominence": "notable"},
            {"name": "Bruno Bucciarati", "prominence": "notable"},
            {"name": "Robert E. O. Speedwagon", "prominence": "deep"},
            {"name": "Jean Pierre Polnareff", "prominence": "deep"},
            {"name": "Muhammad Avdol", "prominence": "deep"},
        ],
    },
    {
        "title": "Princess Mononoke",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "reach": "popular",
        "synopsis": "A cursed prince walks into a war between an industrial iron town and the gods of the forest it is destroying.",
        "characters": [
            {"name": "San", "prominence": "core"},
            {"name": "Ashitaka", "prominence": "core"},
            {"name": "Lady Eboshi", "prominence": "notable"},
            {"name": "Moro", "prominence": "notable"},
            {"name": "Yakul", "prominence": "deep"},
            {"name": "Jigo", "prominence": "deep"},
        ],
    },
    {
        "title": "Howl's Moving Castle",
        "mal_id": None,
        "genres": ["Adventure", "Fantasy", "Romance"],
        "reach": "mega",
        "synopsis": "A girl cursed into old age takes shelter in a walking castle belonging to a vain, powerful wizard during a magical war.",
        "characters": [
            {"name": "Howl", "prominence": "core"},
            {"name": "Sophie Hatter", "prominence": "core"},
            {"name": "Calcifer", "prominence": "core"},
            {"name": "Markl", "prominence": "notable"},
            {"name": "Witch of the Waste", "prominence": "notable"},
            {"name": "Turnip Head", "prominence": "deep"},
            {"name": "Madame Suliman", "prominence": "deep"},
        ],
    },
    {
        "title": "Inuyasha",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy", "Romance"],
        "reach": "popular",
        "synopsis": "A schoolgirl falls down a well into feudal Japan and travels with a half-demon to collect the shards of a shattered jewel.",
        "characters": [
            {"name": "Inuyasha", "prominence": "core"},
            {"name": "Kagome Higurashi", "prominence": "core"},
            {"name": "Sesshomaru", "prominence": "core"},
            {"name": "Miroku", "prominence": "notable"},
            {"name": "Sango", "prominence": "notable"},
            {"name": "Shippo", "prominence": "notable"},
            {"name": "Naraku", "prominence": "notable"},
            {"name": "Kikyo", "prominence": "deep"},
            {"name": "Kirara", "prominence": "deep"},
            {"name": "Rin", "prominence": "deep"},
        ],
    },
    {
        "title": "Soul Eater",
        "mal_id": None,
        "genres": ["Action", "Comedy", "Fantasy", "Supernatural"],
        "reach": "popular",
        "synopsis": "Students at a gothic academy fight alongside partners who transform into weapons, hunting corrupted souls.",
        "characters": [
            {"name": "Maka Albarn", "prominence": "core"},
            {"name": "Soul Evans", "prominence": "core"},
            {"name": "Death the Kid", "prominence": "core"},
            {"name": "Black Star", "prominence": "notable"},
            {"name": "Tsubaki Nakatsukasa", "prominence": "notable"},
            {"name": "Franken Stein", "prominence": "notable"},
            {"name": "Liz Thompson", "prominence": "deep"},
            {"name": "Patty Thompson", "prominence": "deep"},
            {"name": "Excalibur", "prominence": "deep"},
        ],
    },
    {
        "title": "Black Clover",
        "mal_id": None,
        "genres": ["Action", "Comedy", "Fantasy"],
        "reach": "popular",
        "synopsis": "A boy born with no magic in a world defined by it swears to become the wizard king through sheer stubbornness.",
        "characters": [
            {"name": "Asta", "prominence": "core"},
            {"name": "Yuno", "prominence": "core"},
            {"name": "Noelle Silva", "prominence": "core"},
            {"name": "Yami Sukehiro", "prominence": "notable"},
            {"name": "Julius Novachrono", "prominence": "notable"},
            {"name": "Magna Swing", "prominence": "deep"},
            {"name": "Luck Voltia", "prominence": "deep"},
            {"name": "Charmy Pappitson", "prominence": "deep"},
            {"name": "Vanessa Enoteca", "prominence": "deep"},
        ],
    },
    {
        "title": "Dr. Stone",
        "mal_id": None,
        "genres": ["Adventure", "Comedy", "Sci-Fi"],
        "reach": "popular",
        "synopsis": "Humanity is petrified for millennia; a teenage science prodigy revives and rebuilds civilisation from scratch.",
        "characters": [
            {"name": "Senku Ishigami", "prominence": "core"},
            {"name": "Taiju Oki", "prominence": "core"},
            {"name": "Tsukasa Shishio", "prominence": "core"},
            {"name": "Kohaku", "prominence": "notable"},
            {"name": "Chrome", "prominence": "notable"},
            {"name": "Gen Asagiri", "prominence": "notable"},
            {"name": "Yuzuriha Ogawa", "prominence": "deep"},
            {"name": "Suika", "prominence": "deep"},
            {"name": "Ryusui Nanami", "prominence": "deep"},
        ],
    },
    {
        "title": "The Promised Neverland",
        "mal_id": None,
        "genres": ["Mystery", "Psychological", "Thriller"],
        "reach": "popular",
        "synopsis": "Orphans discover their idyllic home is a farm raising them as food, and plan an escape under their caretaker's eye.",
        "characters": [
            {"name": "Emma", "prominence": "core"},
            {"name": "Norman", "prominence": "core"},
            {"name": "Ray", "prominence": "core"},
            {"name": "Isabella", "prominence": "notable"},
            {"name": "Sister Krone", "prominence": "notable"},
            {"name": "Gilda", "prominence": "deep"},
            {"name": "Don", "prominence": "deep"},
            {"name": "Phil", "prominence": "deep"},
        ],
    },
    {
        "title": "Assassination Classroom",
        "mal_id": None,
        "genres": ["Action", "Comedy", "School"],
        "reach": "popular",
        "synopsis": "A class of misfits is tasked with killing their own teacher, a grinning tentacled creature who is also the best teacher they've had.",
        "characters": [
            {"name": "Koro-sensei", "prominence": "core"},
            {"name": "Nagisa Shiota", "prominence": "core"},
            {"name": "Karma Akabane", "prominence": "core"},
            {"name": "Kaede Kayano", "prominence": "notable"},
            {"name": "Tadaomi Karasuma", "prominence": "notable"},
            {"name": "Irina Jelavic", "prominence": "notable"},
            {"name": "Gakushu Asano", "prominence": "deep"},
            {"name": "Ritsu", "prominence": "deep"},
            {"name": "Itona Horibe", "prominence": "deep"},
        ],
    },
    {
        "title": "Kaguya-sama: Love Is War",
        "mal_id": None,
        "genres": ["Comedy", "Psychological", "Romance"],
        "reach": "popular",
        "synopsis": "Two brilliant student council members are in love but each refuses to confess first, turning courtship into psychological warfare.",
        "characters": [
            {"name": "Kaguya Shinomiya", "prominence": "core"},
            {"name": "Miyuki Shirogane", "prominence": "core"},
            {"name": "Chika Fujiwara", "prominence": "core"},
            {"name": "Yu Ishigami", "prominence": "notable"},
            {"name": "Ai Hayasaka", "prominence": "notable"},
            {"name": "Miko Iino", "prominence": "deep"},
            {"name": "Nagisa Kashiwagi", "prominence": "deep"},
        ],
    },
    {
        "title": "Toradora!",
        "mal_id": None,
        "genres": ["Comedy", "Drama", "Romance"],
        "reach": "popular",
        "synopsis": "A tiny, ferocious girl and a boy with a frightening glare team up to set each other up with their respective crushes.",
        "characters": [
            {"name": "Taiga Aisaka", "prominence": "core"},
            {"name": "Ryuuji Takasu", "prominence": "core"},
            {"name": "Minori Kushieda", "prominence": "notable"},
            {"name": "Ami Kawashima", "prominence": "notable"},
            {"name": "Yusaku Kitamura", "prominence": "deep"},
            {"name": "Yasuko Takasu", "prominence": "deep"},
        ],
    },
    {
        "title": "Gintama",
        "mal_id": None,
        "genres": ["Action", "Comedy", "Sci-Fi"],
        "reach": "popular",
        "synopsis": "An idle samurai runs an odd-jobs shop in an alien-occupied Edo, in a comedy that lurches into serious swordplay without warning.",
        "characters": [
            {"name": "Gintoki Sakata", "prominence": "core"},
            {"name": "Kagura", "prominence": "core"},
            {"name": "Shinpachi Shimura", "prominence": "core"},
            {"name": "Toshiro Hijikata", "prominence": "notable"},
            {"name": "Sougo Okita", "prominence": "notable"},
            {"name": "Kotaro Katsura", "prominence": "notable"},
            {"name": "Sadaharu", "prominence": "deep"},
            {"name": "Isao Kondo", "prominence": "deep"},
            {"name": "Tae Shimura", "prominence": "deep"},
        ],
    },
    {
        "title": "That Time I Got Reincarnated as a Slime",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Comedy", "Fantasy"],
        "reach": "popular",
        "synopsis": "A murdered salaryman is reborn as a slime with absorbing powers and builds a nation of monsters.",
        "characters": [
            {"name": "Rimuru Tempest", "prominence": "core"},
            {"name": "Milim Nava", "prominence": "core"},
            {"name": "Shion", "prominence": "notable"},
            {"name": "Shuna", "prominence": "notable"},
            {"name": "Benimaru", "prominence": "notable"},
            {"name": "Veldora Tempest", "prominence": "notable"},
            {"name": "Diablo", "prominence": "deep"},
            {"name": "Souei", "prominence": "deep"},
            {"name": "Gobta", "prominence": "deep"},
        ],
    },
    {
        "title": "Overlord",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "reach": "popular",
        "synopsis": "A player left behind in a shut-down MMO wakes as his skeletal overlord avatar and rules his loyal, terrifying guild.",
        "characters": [
            {"name": "Ainz Ooal Gown", "prominence": "core"},
            {"name": "Albedo", "prominence": "core"},
            {"name": "Shalltear Bloodfallen", "prominence": "notable"},
            {"name": "Demiurge", "prominence": "notable"},
            {"name": "Cocytus", "prominence": "deep"},
            {"name": "Aura Bella Fiora", "prominence": "deep"},
            {"name": "Mare Bello Fiore", "prominence": "deep"},
            {"name": "Sebas Tian", "prominence": "deep"},
        ],
    },
    {
        "title": "Blue Lock",
        "mal_id": None,
        "genres": ["Sports", "Drama"],
        "reach": "popular",
        "synopsis": "Japan locks three hundred strikers in a facility to forge one supremely selfish goal-scorer, eliminating the rest.",
        "characters": [
            {"name": "Yoichi Isagi", "prominence": "core"},
            {"name": "Meguru Bachira", "prominence": "core"},
            {"name": "Rin Itoshi", "prominence": "core"},
            {"name": "Seishiro Nagi", "prominence": "notable"},
            {"name": "Hyoma Chigiri", "prominence": "notable"},
            {"name": "Jinpachi Ego", "prominence": "notable"},
            {"name": "Reo Mikage", "prominence": "deep"},
            {"name": "Sae Itoshi", "prominence": "deep"},
        ],
    },
    {
        "title": "Oshi no Ko",
        "mal_id": None,
        "genres": ["Drama", "Mystery", "Supernatural"],
        "reach": "popular",
        "synopsis": "A doctor and his patient are reborn as the twin children of the idol they adored, growing up inside a ruthless entertainment industry.",
        "characters": [
            {"name": "Ai Hoshino", "prominence": "core"},
            {"name": "Aqua Hoshino", "prominence": "core"},
            {"name": "Ruby Hoshino", "prominence": "core"},
            {"name": "Kana Arima", "prominence": "notable"},
            {"name": "Akane Kurokawa", "prominence": "notable"},
            {"name": "Mem-cho", "prominence": "deep"},
            {"name": "Miyako Saitou", "prominence": "deep"},
        ],
    },
    {
        "title": "Bocchi the Rock!",
        "mal_id": None,
        "genres": ["Comedy", "Music", "Slice of Life"],
        "reach": "popular",
        "synopsis": "A crippingly shy guitarist who practises alone in her closet is dragged into a band and forced onstage.",
        "characters": [
            {"name": "Hitori Gotoh", "prominence": "core"},
            {"name": "Nijika Ijichi", "prominence": "core"},
            {"name": "Ryo Yamada", "prominence": "core"},
            {"name": "Ikuyo Kita", "prominence": "notable"},
            {"name": "Seika Ijichi", "prominence": "deep"},
            {"name": "Kikuri Hiroi", "prominence": "deep"},
        ],
    },
    {
        "title": "Fruits Basket",
        "mal_id": None,
        "genres": ["Drama", "Romance", "Supernatural"],
        "reach": "popular",
        "synopsis": "An orphaned girl lives with a family cursed to transform into zodiac animals when hugged by the opposite sex.",
        "characters": [
            {"name": "Tohru Honda", "prominence": "core"},
            {"name": "Kyo Sohma", "prominence": "core"},
            {"name": "Yuki Sohma", "prominence": "core"},
            {"name": "Shigure Sohma", "prominence": "notable"},
            {"name": "Momiji Sohma", "prominence": "notable"},
            {"name": "Akito Sohma", "prominence": "notable"},
            {"name": "Hatori Sohma", "prominence": "deep"},
            {"name": "Hatsuharu Sohma", "prominence": "deep"},
            {"name": "Kagura Sohma", "prominence": "deep"},
        ],
    },
    {
        "title": "Rurouni Kenshin",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Historical"],
        "reach": "cult",
        "synopsis": "A legendary assassin turned wanderer carries a reversed-blade sword, vowing never to kill again in the early Meiji era.",
        "characters": [
            {"name": "Kenshin Himura", "prominence": "core"},
            {"name": "Kaoru Kamiya", "prominence": "core"},
            {"name": "Sanosuke Sagara", "prominence": "notable"},
            {"name": "Makoto Shishio", "prominence": "notable"},
            {"name": "Hajime Saito", "prominence": "notable"},
            {"name": "Yahiko Myojin", "prominence": "deep"},
            {"name": "Megumi Takani", "prominence": "deep"},
            {"name": "Aoshi Shinomori", "prominence": "deep"},
        ],
    },
    {
        "title": "Psycho-Pass",
        "mal_id": None,
        "genres": ["Action", "Psychological", "Sci-Fi", "Thriller"],
        "reach": "popular",
        "synopsis": "In a society where a scanner measures your likelihood of committing crime, inspectors hunt people flagged before they act.",
        "characters": [
            {"name": "Shinya Kogami", "prominence": "core"},
            {"name": "Akane Tsunemori", "prominence": "core"},
            {"name": "Shogo Makishima", "prominence": "core"},
            {"name": "Nobuchika Ginoza", "prominence": "notable"},
            {"name": "Tomomi Masaoka", "prominence": "deep"},
            {"name": "Shion Karanomori", "prominence": "deep"},
        ],
    },
    {
        "title": "Kill la Kill",
        "mal_id": None,
        "genres": ["Action", "Comedy", "Sci-Fi"],
        "reach": "popular",
        "synopsis": "A girl with a scissor blade storms a school ruled by uniforms that grant superhuman power, hunting her father's killer.",
        "characters": [
            {"name": "Ryuko Matoi", "prominence": "core"},
            {"name": "Satsuki Kiryuin", "prominence": "core"},
            {"name": "Mako Mankanshoku", "prominence": "core"},
            {"name": "Senketsu", "prominence": "notable"},
            {"name": "Nui Harime", "prominence": "notable"},
            {"name": "Ragyo Kiryuin", "prominence": "deep"},
            {"name": "Aikuro Mikisugi", "prominence": "deep"},
        ],
    },
    {
        "title": "Parasyte",
        "mal_id": None,
        "genres": ["Action", "Horror", "Psychological", "Sci-Fi"],
        "reach": "popular",
        "synopsis": "An alien worm takes over a boy's right hand instead of his brain, forcing the two to cooperate against creatures that ate their hosts whole.",
        "characters": [
            {"name": "Shinichi Izumi", "prominence": "core"},
            {"name": "Migi", "prominence": "core"},
            {"name": "Reiko Tamura", "prominence": "notable"},
            {"name": "Satomi Murano", "prominence": "notable"},
            {"name": "Goto", "prominence": "deep"},
            {"name": "Uragami", "prominence": "deep"},
        ],
    },
    {
        "title": "Noragami",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Supernatural"],
        "reach": "popular",
        "synopsis": "A homeless minor god takes odd jobs for five yen, trying to earn a shrine, alongside a girl whose soul keeps slipping out.",
        "characters": [
            {"name": "Yato", "prominence": "core"},
            {"name": "Hiyori Iki", "prominence": "core"},
            {"name": "Yukine", "prominence": "core"},
            {"name": "Bishamon", "prominence": "notable"},
            {"name": "Kofuku", "prominence": "deep"},
            {"name": "Daikoku", "prominence": "deep"},
        ],
    },
    {
        "title": "Dandadan",
        "mal_id": None,
        "genres": ["Action", "Comedy", "Sci-Fi", "Supernatural"],
        "reach": "popular",
        "synopsis": "An occult believer and a ghost sceptic each get proven right, tangling with aliens and spirits at once.",
        "characters": [
            {"name": "Momo Ayase", "prominence": "core"},
            {"name": "Okarun", "prominence": "core"},
            {"name": "Turbo Granny", "prominence": "notable"},
            {"name": "Aira Shiratori", "prominence": "notable"},
            {"name": "Seiko Ayase", "prominence": "deep"},
            {"name": "Jiji", "prominence": "deep"},
        ],
    },
    {
        "title": "Kaiju No. 8",
        "mal_id": None,
        "genres": ["Action", "Sci-Fi"],
        "reach": "popular",
        "synopsis": "A man who cleans up monster corpses gains the ability to become one, and tries to join the defence force that would kill him.",
        "characters": [
            {"name": "Kafka Hibino", "prominence": "core"},
            {"name": "Mina Ashiro", "prominence": "core"},
            {"name": "Reno Ichikawa", "prominence": "notable"},
            {"name": "Kikoru Shinomiya", "prominence": "notable"},
            {"name": "Soshiro Hoshina", "prominence": "deep"},
            {"name": "Gen Narumi", "prominence": "deep"},
        ],
    },
    {
        "title": "The Rising of the Shield Hero",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Drama", "Fantasy"],
        "reach": "popular",
        "synopsis": "A hero summoned with only a shield is framed for a crime and rebuilds from disgrace with a bought slave as his companion.",
        "characters": [
            {"name": "Naofumi Iwatani", "prominence": "core"},
            {"name": "Raphtalia", "prominence": "core"},
            {"name": "Filo", "prominence": "core"},
            {"name": "Melty Melromarc", "prominence": "deep"},
            {"name": "Motoyasu Kitamura", "prominence": "deep"},
            {"name": "Fitoria", "prominence": "deep"},
        ],
    },
    {
        "title": "Erased",
        "mal_id": None,
        "genres": ["Mystery", "Psychological", "Supernatural", "Thriller"],
        "reach": "popular",
        "synopsis": "A man who involuntarily rewinds time to prevent nearby deaths is thrown back to his childhood to stop a serial kidnapper.",
        "characters": [
            {"name": "Satoru Fujinuma", "prominence": "core"},
            {"name": "Kayo Hinazuki", "prominence": "core"},
            {"name": "Gaku Yashiro", "prominence": "notable"},
            {"name": "Airi Katagiri", "prominence": "deep"},
            {"name": "Sachiko Fujinuma", "prominence": "deep"},
        ],
    },
    {
        "title": "Akame ga Kill!",
        "mal_id": None,
        "genres": ["Action", "Drama", "Fantasy"],
        "reach": "popular",
        "synopsis": "A village boy joins a band of assassins working to bring down a corrupt empire, at brutal cost.",
        "characters": [
            {"name": "Akame", "prominence": "core"},
            {"name": "Tatsumi", "prominence": "core"},
            {"name": "Esdeath", "prominence": "core"},
            {"name": "Leone", "prominence": "notable"},
            {"name": "Mine", "prominence": "notable"},
            {"name": "Najenda", "prominence": "deep"},
            {"name": "Lubbock", "prominence": "deep"},
            {"name": "Sheele", "prominence": "deep"},
        ],
    },

    # ---------------------------------------------------------------- cult
    {
        "title": "Steins;Gate",
        "mal_id": None,
        "genres": ["Sci-Fi", "Thriller", "Drama"],
        "reach": "cult",
        "synopsis": "A self-styled mad scientist discovers his microwave can text the past, and every change makes things worse.",
        "characters": [
            {"name": "Rintaro Okabe", "prominence": "core"},
            {"name": "Kurisu Makise", "prominence": "core"},
            {"name": "Mayuri Shiina", "prominence": "core"},
            {"name": "Itaru Hashida", "prominence": "notable"},
            {"name": "Suzuha Amane", "prominence": "notable"},
            {"name": "Faris NyanNyan", "prominence": "deep"},
            {"name": "Luka Urushibara", "prominence": "deep"},
            {"name": "Moeka Kiryu", "prominence": "deep"},
        ],
    },
    {
        "title": "Violet Evergarden",
        "mal_id": None,
        "genres": ["Drama", "Fantasy", "Slice of Life"],
        "reach": "cult",
        "synopsis": "A former child soldier takes work ghostwriting letters for strangers, learning what emotion means through their words.",
        "characters": [
            {"name": "Violet Evergarden", "prominence": "core"},
            {"name": "Gilbert Bougainvillea", "prominence": "core"},
            {"name": "Claudia Hodgins", "prominence": "notable"},
            {"name": "Cattleya Baudelaire", "prominence": "deep"},
            {"name": "Erica Brown", "prominence": "deep"},
            {"name": "Iris Cannary", "prominence": "deep"},
            {"name": "Benedict Blue", "prominence": "deep"},
        ],
    },
    {
        "title": "Vinland Saga",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Drama"],
        "reach": "cult",
        "synopsis": "A boy raised for revenge among Viking mercenaries slowly questions whether violence is worth anything at all.",
        "characters": [
            {"name": "Thorfinn", "prominence": "core"},
            {"name": "Askeladd", "prominence": "core"},
            {"name": "Thors", "prominence": "notable"},
            {"name": "Canute", "prominence": "notable"},
            {"name": "Thorkell", "prominence": "notable"},
            {"name": "Einar", "prominence": "deep"},
            {"name": "Leif Erikson", "prominence": "deep"},
            {"name": "Bjorn", "prominence": "deep"},
        ],
    },
    {
        "title": "Tengen Toppa Gurren Lagann",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Comedy", "Sci-Fi"],
        "reach": "cult",
        "synopsis": "Underground diggers break to the surface and pilot ever-larger drill mecha in an escalating, defiantly over-the-top war.",
        "characters": [
            {"name": "Kamina", "prominence": "core"},
            {"name": "Simon", "prominence": "core"},
            {"name": "Yoko Littner", "prominence": "core"},
            {"name": "Nia Teppelin", "prominence": "notable"},
            {"name": "Viral", "prominence": "deep"},
            {"name": "Rossiu", "prominence": "deep"},
            {"name": "Lordgenome", "prominence": "deep"},
        ],
    },
    {
        "title": "KonoSuba: God's Blessing on This Wonderful World!",
        "mal_id": None,
        "genres": ["Comedy", "Fantasy", "Adventure"],
        "reach": "cult",
        "synopsis": "A dead shut-in is reincarnated into a fantasy world and saddled with a useless goddess, an explosion-obsessed mage, and a masochistic knight.",
        "characters": [
            {"name": "Kazuma Sato", "prominence": "core"},
            {"name": "Aqua", "prominence": "core"},
            {"name": "Megumin", "prominence": "core"},
            {"name": "Darkness", "prominence": "core"},
            {"name": "Wiz", "prominence": "notable"},
            {"name": "Yunyun", "prominence": "notable"},
            {"name": "Chris", "prominence": "deep"},
        ],
    },
    {
        "title": "Trigun",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "reach": "cult",
        "synopsis": "A pacifist gunman with an enormous bounty wanders a desert planet, trailed by disaster he swears he did not cause.",
        "characters": [
            {"name": "Vash the Stampede", "prominence": "core"},
            {"name": "Nicholas D. Wolfwood", "prominence": "core"},
            {"name": "Meryl Stryfe", "prominence": "notable"},
            {"name": "Millions Knives", "prominence": "notable"},
            {"name": "Milly Thompson", "prominence": "deep"},
        ],
    },
    {
        "title": "Monster",
        "mal_id": None,
        "genres": ["Drama", "Mystery", "Psychological", "Thriller"],
        "reach": "cult",
        "synopsis": "A surgeon saves a boy's life and spends years hunting him after realising he has grown into a serial killer.",
        "characters": [
            {"name": "Kenzo Tenma", "prominence": "core"},
            {"name": "Johan Liebert", "prominence": "core"},
            {"name": "Nina Fortner", "prominence": "notable"},
            {"name": "Heinrich Lunge", "prominence": "notable"},
            {"name": "Eva Heinemann", "prominence": "deep"},
            {"name": "Wolfgang Grimmer", "prominence": "deep"},
        ],
    },
    {
        "title": "The Apothecary Diaries",
        "mal_id": None,
        "genres": ["Mystery", "Drama", "Historical"],
        "reach": "popular",
        "synopsis": "A pharmacist's apprentice sold into the imperial palace quietly solves poisonings and court intrigue while trying to avoid being promoted.",
        "characters": [
            {"name": "Maomao", "prominence": "core"},
            {"name": "Jinshi", "prominence": "core"},
            {"name": "Gaoshun", "prominence": "notable"},
            {"name": "Consort Gyokuyou", "prominence": "notable"},
            {"name": "Consort Lihua", "prominence": "notable"},
            {"name": "Luomen", "prominence": "notable"},
            {"name": "Lakan", "prominence": "notable"},
            {"name": "Xiaolan", "prominence": "deep"},
            {"name": "Consort Lishu", "prominence": "deep"},
            {"name": "Suirei", "prominence": "deep"},
        ],
    },
]
