"""Character pool data.

Jikan (MyAnimeList's API) has been experiencing a sustained outage during
development of this project -- every anime in build_character_pool.py's
target list failed, including ones (like One Piece) that had worked earlier
in the same session. Rather than ship an empty pool, this file was hand
-curated directly from known, real casts of well-known anime.

"role" here is NOT a literal copy of MAL's own Main/Supporting tag -- it's a
judgment call on general-audience recognizability, per direction from the
project owner: a newer, currently-viral show's supporting cast (Gojo in
Jujutsu Kaisen, Makima in Chainsaw Man) can be more recognizable than an
older or more niche show's lead, so difficulty is weighted by how
mainstream the character actually is, not just their narrative centrality.

`mal_id: None` marks an entry as curated this way rather than confirmed via
a live Jikan lookup. Re-running build_character_pool.py once Jikan recovers
will overwrite this file with live-sourced data (and real mal_ids) --
nothing else in the app needs to change for that swap. Genre/role judgment
calls made here would likely need re-reconciling by hand afterward, since a
fresh Jikan pull would revert to MAL's literal role tags.
"""

ANIME_POOL = [
    {
        "title": "Naruto",
        "mal_id": None,
        "genres": ["Action", "Adventure"],
        "characters": [
            {"name": "Naruto Uzumaki", "role": "Main"},
            {"name": "Sasuke Uchiha", "role": "Main"},
            {"name": "Sakura Haruno", "role": "Main"},
            {"name": "Kakashi Hatake", "role": "Main"},
            {"name": "Rock Lee", "role": "Supporting"},
            {"name": "Hinata Hyuga", "role": "Supporting"},
            {"name": "Shikamaru Nara", "role": "Supporting"},
            {"name": "Gaara", "role": "Supporting"},
            {"name": "Itachi Uchiha", "role": "Supporting"},
            {"name": "Jiraiya", "role": "Supporting"},
            {"name": "Tsunade", "role": "Supporting"},
            {"name": "Might Guy", "role": "Supporting"},
            {"name": "Neji Hyuga", "role": "Supporting"},
            {"name": "Kiba Inuzuka", "role": "Supporting"},
            {"name": "Choji Akimichi", "role": "Supporting"},
            {"name": "Ino Yamanaka", "role": "Supporting"},
            {"name": "Orochimaru", "role": "Supporting"},
            {"name": "Minato Namikaze", "role": "Supporting"},
        ],
    },
    {
        "title": "One Piece",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "characters": [
            {"name": "Monkey D. Luffy", "role": "Main"},
            {"name": "Roronoa Zoro", "role": "Main"},
            {"name": "Nami", "role": "Main"},
            {"name": "Usopp", "role": "Main"},
            {"name": "Sanji", "role": "Main"},
            {"name": "Tony Tony Chopper", "role": "Supporting"},
            {"name": "Nico Robin", "role": "Supporting"},
            {"name": "Franky", "role": "Supporting"},
            {"name": "Brook", "role": "Supporting"},
            {"name": "Jinbe", "role": "Supporting"},
            {"name": "Portgas D. Ace", "role": "Supporting"},
            {"name": "Trafalgar Law", "role": "Supporting"},
            {"name": "Boa Hancock", "role": "Supporting"},
            {"name": "Shanks", "role": "Supporting"},
        ],
    },
    {
        "title": "Death Note",
        "mal_id": None,
        "genres": ["Mystery", "Psychological", "Supernatural"],
        "characters": [
            {"name": "Light Yagami", "role": "Main"},
            {"name": "L", "role": "Main"},
            {"name": "Misa Amane", "role": "Supporting"},
            {"name": "Ryuk", "role": "Supporting"},
            {"name": "Near", "role": "Supporting"},
            {"name": "Mello", "role": "Supporting"},
            {"name": "Soichiro Yagami", "role": "Supporting"},
            {"name": "Teru Mikami", "role": "Supporting"},
        ],
    },
    {
        "title": "Attack on Titan",
        "mal_id": None,
        "genres": ["Action", "Drama", "Fantasy", "Mystery"],
        "characters": [
            {"name": "Eren Yeager", "role": "Main"},
            {"name": "Mikasa Ackerman", "role": "Main"},
            {"name": "Armin Arlert", "role": "Main"},
            {"name": "Levi Ackerman", "role": "Main"},
            {"name": "Erwin Smith", "role": "Main"},
            {"name": "Historia Reiss", "role": "Main"},
            {"name": "Reiner Braun", "role": "Supporting"},
            {"name": "Jean Kirstein", "role": "Supporting"},
            {"name": "Sasha Blouse", "role": "Supporting"},
            {"name": "Connie Springer", "role": "Supporting"},
            {"name": "Ymir", "role": "Supporting"},
            {"name": "Annie Leonhart", "role": "Supporting"},
            {"name": "Hange Zoe", "role": "Supporting"},
        ],
    },
    {
        "title": "My Hero Academia",
        "mal_id": None,
        "genres": ["Action", "Adventure"],
        "characters": [
            {"name": "Izuku Midoriya", "role": "Main"},
            {"name": "Katsuki Bakugo", "role": "Main"},
            {"name": "Ochaco Uraraka", "role": "Main"},
            {"name": "All Might", "role": "Main"},
            {"name": "Shoto Todoroki", "role": "Supporting"},
            {"name": "Tenya Iida", "role": "Supporting"},
            {"name": "Tsuyu Asui", "role": "Supporting"},
            {"name": "Eijiro Kirishima", "role": "Supporting"},
            {"name": "Denki Kaminari", "role": "Supporting"},
            {"name": "Momo Yaoyorozu", "role": "Supporting"},
            {"name": "Shota Aizawa", "role": "Supporting"},
            {"name": "Endeavor", "role": "Supporting"},
            {"name": "Tomura Shigaraki", "role": "Supporting"},
        ],
    },
    {
        "title": "Demon Slayer: Kimetsu no Yaiba",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "characters": [
            {"name": "Tanjiro Kamado", "role": "Main"},
            {"name": "Nezuko Kamado", "role": "Main"},
            {"name": "Zenitsu Agatsuma", "role": "Main"},
            {"name": "Inosuke Hashibira", "role": "Main"},
            {"name": "Kyojuro Rengoku", "role": "Main"},
            {"name": "Muzan Kibutsuji", "role": "Main"},
            {"name": "Akaza", "role": "Main"},
            {"name": "Giyu Tomioka", "role": "Supporting"},
            {"name": "Shinobu Kocho", "role": "Supporting"},
            {"name": "Tengen Uzui", "role": "Supporting"},
            {"name": "Kanao Tsuyuri", "role": "Supporting"},
        ],
    },
    {
        "title": "Fullmetal Alchemist: Brotherhood",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Drama", "Fantasy"],
        "characters": [
            {"name": "Edward Elric", "role": "Main"},
            {"name": "Alphonse Elric", "role": "Main"},
            {"name": "Winry Rockbell", "role": "Supporting"},
            {"name": "Roy Mustang", "role": "Supporting"},
            {"name": "Riza Hawkeye", "role": "Supporting"},
            {"name": "Alex Louis Armstrong", "role": "Supporting"},
            {"name": "Scar", "role": "Supporting"},
            {"name": "Ling Yao", "role": "Supporting"},
            {"name": "May Chang", "role": "Supporting"},
            {"name": "King Bradley", "role": "Supporting"},
            {"name": "Envy", "role": "Supporting"},
            {"name": "Greed", "role": "Supporting"},
        ],
    },
    {
        "title": "Jujutsu Kaisen",
        "mal_id": None,
        "genres": ["Action", "Fantasy", "Horror"],
        "characters": [
            {"name": "Yuji Itadori", "role": "Main"},
            {"name": "Megumi Fushiguro", "role": "Main"},
            {"name": "Nobara Kugisaki", "role": "Main"},
            {"name": "Satoru Gojo", "role": "Main"},
            {"name": "Sukuna", "role": "Main"},
            {"name": "Maki Zenin", "role": "Supporting"},
            {"name": "Nanami Kento", "role": "Supporting"},
            {"name": "Toge Inumaki", "role": "Supporting"},
            {"name": "Panda", "role": "Supporting"},
            {"name": "Yuta Okkotsu", "role": "Supporting"},
        ],
    },
    {
        "title": "Tokyo Ghoul",
        "mal_id": None,
        "genres": ["Action", "Drama", "Horror", "Mystery"],
        "characters": [
            {"name": "Ken Kaneki", "role": "Main"},
            {"name": "Touka Kirishima", "role": "Supporting"},
            {"name": "Rize Kamishiro", "role": "Supporting"},
            {"name": "Hideyoshi Nagachika", "role": "Supporting"},
            {"name": "Renji Yomo", "role": "Supporting"},
            {"name": "Juzo Suzuya", "role": "Supporting"},
            {"name": "Kishou Arima", "role": "Supporting"},
            {"name": "Shuu Tsukiyama", "role": "Supporting"},
        ],
    },
    {
        "title": "Haikyuu!!",
        "mal_id": None,
        "genres": ["Sports", "Comedy", "Drama"],
        "characters": [
            {"name": "Shoyo Hinata", "role": "Main"},
            {"name": "Tobio Kageyama", "role": "Main"},
            {"name": "Daichi Sawamura", "role": "Supporting"},
            {"name": "Koshi Sugawara", "role": "Supporting"},
            {"name": "Ryunosuke Tanaka", "role": "Supporting"},
            {"name": "Kei Tsukishima", "role": "Supporting"},
            {"name": "Yu Nishinoya", "role": "Supporting"},
            {"name": "Tooru Oikawa", "role": "Supporting"},
            {"name": "Kenma Kozume", "role": "Supporting"},
            {"name": "Kotaro Bokuto", "role": "Supporting"},
        ],
    },
    {
        "title": "Bleach",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "characters": [
            {"name": "Ichigo Kurosaki", "role": "Main"},
            {"name": "Rukia Kuchiki", "role": "Main"},
            {"name": "Orihime Inoue", "role": "Supporting"},
            {"name": "Uryu Ishida", "role": "Supporting"},
            {"name": "Yasutora Sado", "role": "Supporting"},
            {"name": "Renji Abarai", "role": "Supporting"},
            {"name": "Byakuya Kuchiki", "role": "Supporting"},
            {"name": "Toshiro Hitsugaya", "role": "Supporting"},
            {"name": "Kenpachi Zaraki", "role": "Supporting"},
            {"name": "Sosuke Aizen", "role": "Supporting"},
        ],
    },
    {
        "title": "Fairy Tail",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "characters": [
            {"name": "Natsu Dragneel", "role": "Main"},
            {"name": "Lucy Heartfilia", "role": "Main"},
            {"name": "Gray Fullbuster", "role": "Supporting"},
            {"name": "Erza Scarlet", "role": "Supporting"},
            {"name": "Wendy Marvell", "role": "Supporting"},
            {"name": "Gajeel Redfox", "role": "Supporting"},
            {"name": "Happy", "role": "Supporting"},
            {"name": "Juvia Lockser", "role": "Supporting"},
            {"name": "Laxus Dreyar", "role": "Supporting"},
        ],
    },
    {
        "title": "Sword Art Online",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy", "Romance"],
        "characters": [
            {"name": "Kirito", "role": "Main"},
            {"name": "Asuna Yuuki", "role": "Main"},
            {"name": "Klein", "role": "Supporting"},
            {"name": "Silica", "role": "Supporting"},
            {"name": "Lisbeth", "role": "Supporting"},
            {"name": "Sinon", "role": "Supporting"},
            {"name": "Leafa", "role": "Supporting"},
            {"name": "Yui", "role": "Supporting"},
            {"name": "Heathcliff", "role": "Supporting"},
        ],
    },
    {
        "title": "Code Geass: Lelouch of the Rebellion",
        "mal_id": None,
        "genres": ["Action", "Drama", "Mecha", "Sci-Fi"],
        "characters": [
            {"name": "Lelouch Lamperouge", "role": "Main"},
            {"name": "Suzaku Kururugi", "role": "Supporting"},
            {"name": "C.C.", "role": "Supporting"},
            {"name": "Kallen Kozuki", "role": "Supporting"},
            {"name": "Nunnally Lamperouge", "role": "Supporting"},
            {"name": "Shirley Fenette", "role": "Supporting"},
            {"name": "Rolo Lamperouge", "role": "Supporting"},
        ],
    },
    {
        "title": "Spy x Family",
        "mal_id": None,
        "genres": ["Action", "Comedy", "Childcare"],
        "characters": [
            {"name": "Loid Forger", "role": "Main"},
            {"name": "Yor Forger", "role": "Main"},
            {"name": "Anya Forger", "role": "Main"},
            {"name": "Bond Forger", "role": "Supporting"},
            {"name": "Yuri Briar", "role": "Supporting"},
            {"name": "Fiona Frost", "role": "Supporting"},
            {"name": "Damian Desmond", "role": "Supporting"},
            {"name": "Becky Blackbell", "role": "Supporting"},
        ],
    },
    {
        "title": "Chainsaw Man",
        "mal_id": None,
        "genres": ["Action", "Fantasy", "Horror"],
        "characters": [
            {"name": "Denji", "role": "Main"},
            {"name": "Power", "role": "Main"},
            {"name": "Aki Hayakawa", "role": "Main"},
            {"name": "Makima", "role": "Main"},
            {"name": "Reze", "role": "Main"},
            {"name": "Himeno", "role": "Supporting"},
            {"name": "Kishibe", "role": "Supporting"},
            {"name": "Angel Devil", "role": "Supporting"},
        ],
    },
    {
        "title": "One Punch Man",
        "mal_id": None,
        "genres": ["Action", "Comedy", "Sci-Fi"],
        "characters": [
            {"name": "Saitama", "role": "Main"},
            {"name": "Genos", "role": "Main"},
            {"name": "Bang", "role": "Supporting"},
            {"name": "Tatsumaki", "role": "Supporting"},
            {"name": "Fubuki", "role": "Supporting"},
            {"name": "King", "role": "Supporting"},
            {"name": "Mumen Rider", "role": "Supporting"},
            {"name": "Speed-o'-Sound Sonic", "role": "Supporting"},
        ],
    },
    {
        "title": "Hunter x Hunter",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "characters": [
            {"name": "Gon Freecss", "role": "Main"},
            {"name": "Killua Zoldyck", "role": "Main"},
            {"name": "Kurapika", "role": "Supporting"},
            {"name": "Leorio Paradinight", "role": "Supporting"},
            {"name": "Hisoka Morow", "role": "Supporting"},
            {"name": "Chrollo Lucilfer", "role": "Supporting"},
            {"name": "Meruem", "role": "Supporting"},
            {"name": "Biscuit Krueger", "role": "Supporting"},
        ],
    },
    {
        "title": "Steins;Gate",
        "mal_id": None,
        "genres": ["Sci-Fi", "Thriller", "Drama"],
        "characters": [
            {"name": "Rintaro Okabe", "role": "Main"},
            {"name": "Kurisu Makise", "role": "Supporting"},
            {"name": "Mayuri Shiina", "role": "Supporting"},
            {"name": "Itaru Hashida", "role": "Supporting"},
            {"name": "Suzuha Amane", "role": "Supporting"},
            {"name": "Faris NyanNyan", "role": "Supporting"},
            {"name": "Luka Urushibara", "role": "Supporting"},
        ],
    },
    {
        "title": "Violet Evergarden",
        "mal_id": None,
        "genres": ["Drama", "Fantasy", "Slice of Life"],
        "characters": [
            {"name": "Violet Evergarden", "role": "Main"},
            {"name": "Gilbert Bougainvillea", "role": "Supporting"},
            {"name": "Claudia Hodgins", "role": "Supporting"},
            {"name": "Cattleya Baudelaire", "role": "Supporting"},
            {"name": "Erica Brown", "role": "Supporting"},
            {"name": "Iris Cannary", "role": "Supporting"},
        ],
    },
    {
        "title": "Dragon Ball Z",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Fantasy"],
        "characters": [
            {"name": "Goku", "role": "Main"},
            {"name": "Vegeta", "role": "Main"},
            {"name": "Gohan", "role": "Main"},
            {"name": "Piccolo", "role": "Main"},
            {"name": "Bulma", "role": "Supporting"},
            {"name": "Krillin", "role": "Supporting"},
            {"name": "Trunks", "role": "Supporting"},
            {"name": "Frieza", "role": "Supporting"},
            {"name": "Cell", "role": "Supporting"},
            {"name": "Majin Buu", "role": "Supporting"},
        ],
    },
    {
        "title": "Cowboy Bebop",
        "mal_id": None,
        "genres": ["Action", "Sci-Fi", "Space", "Adventure"],
        "characters": [
            {"name": "Spike Spiegel", "role": "Main"},
            {"name": "Jet Black", "role": "Supporting"},
            {"name": "Faye Valentine", "role": "Supporting"},
            {"name": "Ed", "role": "Supporting"},
            {"name": "Ein", "role": "Supporting"},
            {"name": "Vicious", "role": "Supporting"},
            {"name": "Julia", "role": "Supporting"},
        ],
    },
    {
        "title": "Neon Genesis Evangelion",
        "mal_id": None,
        "genres": ["Action", "Drama", "Mecha", "Psychological", "Sci-Fi"],
        "characters": [
            {"name": "Shinji Ikari", "role": "Main"},
            {"name": "Rei Ayanami", "role": "Main"},
            {"name": "Asuka Langley Soryu", "role": "Main"},
            {"name": "Misato Katsuragi", "role": "Supporting"},
            {"name": "Gendo Ikari", "role": "Supporting"},
            {"name": "Kaworu Nagisa", "role": "Supporting"},
            {"name": "Ritsuko Akagi", "role": "Supporting"},
        ],
    },
    {
        "title": "Mob Psycho 100",
        "mal_id": None,
        "genres": ["Action", "Comedy", "Supernatural"],
        "characters": [
            {"name": "Shigeo Kageyama", "role": "Main"},
            {"name": "Reigen Arataka", "role": "Main"},
            {"name": "Dimple", "role": "Supporting"},
            {"name": "Ritsu Kageyama", "role": "Supporting"},
            {"name": "Teruki Hanazawa", "role": "Supporting"},
            {"name": "Tome Kurata", "role": "Supporting"},
        ],
    },
    {
        "title": "Re:Zero − Starting Life in Another World",
        "mal_id": None,
        "genres": ["Drama", "Fantasy", "Psychological", "Thriller"],
        "characters": [
            {"name": "Subaru Natsuki", "role": "Main"},
            {"name": "Emilia", "role": "Main"},
            {"name": "Rem", "role": "Supporting"},
            {"name": "Ram", "role": "Supporting"},
            {"name": "Beatrice", "role": "Supporting"},
            {"name": "Puck", "role": "Supporting"},
            {"name": "Roswaal L Mathers", "role": "Supporting"},
            {"name": "Crusch Karlchan", "role": "Supporting"},
        ],
    },
    {
        "title": "KonoSuba: God's Blessing on This Wonderful World!",
        "mal_id": None,
        "genres": ["Comedy", "Fantasy", "Adventure"],
        "characters": [
            {"name": "Kazuma Sato", "role": "Supporting"},
            {"name": "Aqua", "role": "Supporting"},
            {"name": "Megumin", "role": "Supporting"},
            {"name": "Darkness", "role": "Supporting"},
            {"name": "Wiz", "role": "Supporting"},
            {"name": "Yunyun", "role": "Supporting"},
        ],
    },
    {
        "title": "Fate/Zero",
        "mal_id": None,
        "genres": ["Action", "Fantasy", "Supernatural"],
        "characters": [
            {"name": "Saber", "role": "Main"},
            {"name": "Kiritsugu Emiya", "role": "Supporting"},
            {"name": "Kirei Kotomine", "role": "Supporting"},
            {"name": "Iskandar", "role": "Supporting"},
            {"name": "Waver Velvet", "role": "Supporting"},
            {"name": "Gilgamesh", "role": "Supporting"},
            {"name": "Kariya Matou", "role": "Supporting"},
            {"name": "Tokiomi Tohsaka", "role": "Supporting"},
        ],
    },
    {
        "title": "Frieren: Beyond Journey's End",
        "mal_id": None,
        "genres": ["Adventure", "Drama", "Fantasy"],
        "characters": [
            {"name": "Frieren", "role": "Main"},
            {"name": "Fern", "role": "Main"},
            {"name": "Stark", "role": "Main"},
            {"name": "Himmel", "role": "Supporting"},
            {"name": "Heiter", "role": "Supporting"},
            {"name": "Eisen", "role": "Supporting"},
            {"name": "Serie", "role": "Supporting"},
        ],
    },
    {
        "title": "Solo Leveling",
        "mal_id": None,
        "genres": ["Action", "Fantasy"],
        "characters": [
            {"name": "Sung Jinwoo", "role": "Main"},
            {"name": "Cha Hae-In", "role": "Main"},
            {"name": "Go Gun-hee", "role": "Supporting"},
            {"name": "Baek Yoonho", "role": "Supporting"},
            {"name": "Woo Jinchul", "role": "Supporting"},
        ],
    },
    {
        "title": "Vinland Saga",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Drama"],
        "characters": [
            {"name": "Thorfinn", "role": "Main"},
            {"name": "Askeladd", "role": "Supporting"},
            {"name": "Canute", "role": "Supporting"},
            {"name": "Einar", "role": "Supporting"},
            {"name": "Thorkell", "role": "Supporting"},
            {"name": "Leif Erikson", "role": "Supporting"},
        ],
    },
    {
        "title": "Tengen Toppa Gurren Lagann",
        "mal_id": None,
        "genres": ["Action", "Adventure", "Comedy", "Sci-Fi"],
        "characters": [
            {"name": "Simon", "role": "Main"},
            {"name": "Kamina", "role": "Supporting"},
            {"name": "Yoko Littner", "role": "Supporting"},
            {"name": "Nia Teppelin", "role": "Supporting"},
            {"name": "Viral", "role": "Supporting"},
        ],
    },
    {
        "title": "Your Name",
        "mal_id": None,
        "genres": ["Romance", "Drama", "Supernatural"],
        "characters": [
            {"name": "Taki Tachibana", "role": "Main"},
            {"name": "Mitsuha Miyamizu", "role": "Main"},
            {"name": "Katsuhiko Teshigawara", "role": "Supporting"},
            {"name": "Sayaka Natori", "role": "Supporting"},
            {"name": "Yotsuha Miyamizu", "role": "Supporting"},
        ],
    },
]
