import random

from character_pool_data import ANIME_POOL

# role is MAL's own "how central is this character" tag ("Main" | "Supporting"),
# which is a far more reliable difficulty signal than trying to threshold a
# favorites count that varies wildly in scale between franchises.
EASY_ROLE = "Main"
HARD_ROLE = "Supporting"


def _filter_by_difficulty(characters: list[dict], difficulty: str) -> list[dict]:
    tier = EASY_ROLE if difficulty == "easy" else HARD_ROLE
    candidates = [c for c in characters if c["role"] == tier]
    return candidates or characters


async def get_character(difficulty: str = "easy") -> dict:
    """Picks a random character from the static, pre-built pool
    (character_pool_data.py, generated by build_character_pool.py). This is
    the ONLY character source used during actual gameplay -- no network
    call, so starting a round is instant and never depends on Jikan being
    up. The live Jikan lookup in main.py's /api/character-details endpoint
    is a completely separate, decorative, post-game-only feature and does
    not feed back into this."""
    anime = random.choice(ANIME_POOL)
    candidates = _filter_by_difficulty(anime["characters"], difficulty)
    chosen = random.choice(candidates)
    return {
        "character": chosen["name"],
        "character_role": chosen["role"],
        "anime_title": anime["title"],
        "genres": anime["genres"],
    }
