import functools
import random

from character_pool_data import ANIME_POOL

# role is MAL's own "how central is this character" tag ("Main" | "Supporting"),
# which is a far more reliable difficulty signal than trying to threshold a
# favorites count that varies wildly in scale between franchises.
EASY_ROLE = "Main"
HARD_ROLE = "Supporting"


def _filter_by_difficulty(characters: list[dict], difficulty: str) -> list[dict]:
    tier = EASY_ROLE if difficulty == "easy" else HARD_ROLE
    candidates = [c for c in characters if c["role"] == tier]
    return candidates or characters


def _pick_decoy(anime: dict, chosen: dict, difficulty: str) -> "str | None":
    """A different character from the SAME anime, for the Undercover-style
    imposter mode. Prefers the same difficulty tier so the decoy is a
    comparable name, but will take any other character from the show rather
    than give up -- a same-series decoy is what makes the imposter's hints
    plausible instead of pure guesswork. Returns None only when the anime
    genuinely has nobody else."""
    same_tier = [c for c in _filter_by_difficulty(anime["characters"], difficulty)
                 if c["name"] != chosen["name"]]
    if same_tier:
        return random.choice(same_tier)["name"]

    anyone_else = [c for c in anime["characters"] if c["name"] != chosen["name"]]
    return random.choice(anyone_else)["name"] if anyone_else else None


@functools.lru_cache(maxsize=4)
def pool_entries(difficulty: str) -> tuple:
    """Every character a game at this difficulty could possibly have chosen,
    as ((id, name), ...) sorted by name.

    This is what the ejected imposter picks from for their last-chance guess,
    instead of typing a name from memory. Deliberately the WHOLE tier, never
    just the current anime's cast -- narrowing it to one show would hand them
    the answer. Seeing ~80-200 names tells them nothing they didn't already
    know, since the difficulty setting is shown in the lobby anyway.

    Cached because it's rebuilt on every guess phase and the underlying pool
    is a static import that never changes at runtime.

    Built through _filter_by_difficulty rather than by re-filtering on role,
    so it lands on exactly the set get_character() can actually return. That
    matters: _filter_by_difficulty falls back to an anime's whole cast when it
    has nobody in the requested tier (KonoSuba has no "Main" entries at all),
    so a role-based filter here would omit characters an easy game can genuinely
    choose -- and the guesser would have no way to pick the right answer.
    """
    names = {
        c["name"]
        for anime in ANIME_POOL
        for c in _filter_by_difficulty(anime["characters"], difficulty)
    }
    # Index-as-id is stable for the process because the sort is total and the
    # source data is immutable; the server re-derives the name from the id at
    # submit time, so a client never gets to define what a given id means.
    return tuple((index, name) for index, name in enumerate(sorted(names)))


def resolve_pool_entry(difficulty: str, entry_id) -> "str | None":
    """Turn a client-supplied pool id back into a character name, or None."""
    if not isinstance(entry_id, int) or isinstance(entry_id, bool):
        return None
    entries = pool_entries(difficulty)
    if 0 <= entry_id < len(entries):
        return entries[entry_id][1]
    return None


async def get_character(difficulty: str = "easy") -> dict:
    """Picks a random character from the static, pre-built pool
    (character_pool_data.py, generated by build_character_pool.py). This is
    the ONLY character source used during actual gameplay -- no network
    call, so starting a round is instant and never depends on Jikan being
    up. The live Jikan lookup in main.py's /api/character-details endpoint
    is a completely separate, decorative, post-game-only feature and does
    not feed back into this.

    `decoy` is the alternate same-series character handed to imposters in
    "similar" mode; it is always computed but only ever sent to a client
    when that mode is on."""
    anime = random.choice(ANIME_POOL)
    candidates = _filter_by_difficulty(anime["characters"], difficulty)
    chosen = random.choice(candidates)
    return {
        "character": chosen["name"],
        "character_role": chosen["role"],
        "anime_title": anime["title"],
        "genres": anime["genres"],
        "decoy": _pick_decoy(anime, chosen, difficulty),
    }
